services:
  - type: web
    name: premium-loader
    env: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: SCRIPT_SOURCE_URL
        sync: false
      - key: SCRIPT_ALREADY_OBFUSCATED
        sync: false
      - key: WHITELIST_USER_IDS
        sync: false
      - key: OWNER_USER_IDS
        sync: false
      - key: ALLOWED_PLACE_IDS
        sync: false
      - key: ADMIN_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
